modLoader="javafml"
loaderVersion="31.2.31"
license="Modified MIT license. See LICENSE.md for details"
[[mods]]
modId="simplebackpacks" 
version="1"
displayName="Simple Backpacks"
# The description text for the mod (multi line!) (#mandatory)
description='''
Adds simple four different tiered backpacks.
'''

[[dependencies.ironbackpacks]]
    modId="forge"
    mandatory=true
    versionRange="33.0.0"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.ironbackpacks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"
